inherit_from: .rubocop_todo.yml

Layout/ExtraSpacing:
  Exclude:
    - 'spec/**/**.rb'
Layout/SpaceInsideParens:
  Exclude:
    - 'spec/**/**.rb'
Metrics/AbcSize:
  Max: 15
Metrics/MethodLength:
  Max: 10
Naming/MethodParameterName:
  AllowedNames:
    - i
    - j
    - k
    - m
    - n
